-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-04-13 00:55:27.188

-- tables
-- Table: CIDADES
CREATE TABLE CIDADES (
    ID_CIDADE bigint NOT NULL,
    DES_CIDADE varchar(100) NOT NULL,
    DES_SIGLA_ESTADO char(2) NOT NULL,
    DES_REGIAO_IBGE varchar(20) NOT NULL,
    CONSTRAINT CIDADES_pk PRIMARY KEY (ID_CIDADE)
);

-- Table: CNAE
CREATE TABLE CNAE (
    ID_CNAE bigint NOT NULL,
    COD_CNAE varchar(50) NOT NULL,
    DES_CNAE varchar(200) NOT NULL,
    UNIQUE INDEX CNAE_ak_1 (COD_CNAE),
    CONSTRAINT CNAE_pk PRIMARY KEY (ID_CNAE)
);

-- Table: CONSUMO
CREATE TABLE CONSUMO (
    ID_CONSUMO bigint NOT NULL AUTO_INCREMENT,
    QTD_CONSUMO int NOT NULL,
    EMPRESAS_CNPJ varchar(30) NOT NULL,
    MES_REFERENCIA timestamp NOT NULL,
    CONSTRAINT CONSUMO_pk PRIMARY KEY (ID_CONSUMO)
) ENGINE InnoDB;

-- Table: EMPRESAS
CREATE TABLE EMPRESAS (
    CNPJ varchar(20) NOT NULL,
    CIDADES_ID_CIDADE bigint NOT NULL,
    CNAE_ID_CNAE bigint NOT NULL,
    ORIGEM varchar(20) NOT NULL,
    UNIQUE INDEX EMPRESAS_ak_1 (CNPJ),
    CONSTRAINT EMPRESAS_pk PRIMARY KEY (CNPJ)
);

-- Table: USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO bigint NOT NULL AUTO_INCREMENT,
    NOME varchar(255) NOT NULL,
    EMAIL varchar(255) NOT NULL,
    SENHA varchar(255) NOT NULL,
    NIVEL varchar(40) NOT NULL,
    CONSTRAINT USUARIOS_pk PRIMARY KEY (ID_USUARIO)
);

-- Table: VENDAS
CREATE TABLE VENDAS (
    ID_VENDA bigint NOT NULL AUTO_INCREMENT,
    CONSUMO_ID_CONSUMO bigint NOT NULL,
    CNAE_ID_CNAE bigint NOT NULL,
    CIDADES_ID_CIDADE bigint NOT NULL,
    EMPRESAS_CNPJ varchar(20) NOT NULL,
    USUARIOS_ID_USUARIO bigint NOT NULL,
    CONSTRAINT VENDAS_pk PRIMARY KEY (ID_VENDA)
) COMMENT 'Tabela Fato';

-- foreign keys
-- Reference: CONSUMO_EMPRESAS (table: CONSUMO)
ALTER TABLE CONSUMO ADD CONSTRAINT CONSUMO_EMPRESAS FOREIGN KEY CONSUMO_EMPRESAS (EMPRESAS_CNPJ)
    REFERENCES EMPRESAS (CNPJ);

-- Reference: EMPRESAS_CIDADES (table: EMPRESAS)
ALTER TABLE EMPRESAS ADD CONSTRAINT EMPRESAS_CIDADES FOREIGN KEY EMPRESAS_CIDADES (CIDADES_ID_CIDADE)
    REFERENCES CIDADES (ID_CIDADE);

-- Reference: EMPRESAS_CNAE (table: EMPRESAS)
ALTER TABLE EMPRESAS ADD CONSTRAINT EMPRESAS_CNAE FOREIGN KEY EMPRESAS_CNAE (CNAE_ID_CNAE)
    REFERENCES CNAE (ID_CNAE);

-- Reference: VENDAS_CIDADES (table: VENDAS)
ALTER TABLE VENDAS ADD CONSTRAINT VENDAS_CIDADES FOREIGN KEY VENDAS_CIDADES (CIDADES_ID_CIDADE)
    REFERENCES CIDADES (ID_CIDADE);

-- Reference: VENDAS_CNAE (table: VENDAS)
ALTER TABLE VENDAS ADD CONSTRAINT VENDAS_CNAE FOREIGN KEY VENDAS_CNAE (CNAE_ID_CNAE)
    REFERENCES CNAE (ID_CNAE);

-- Reference: VENDAS_CONSUMO (table: VENDAS)
ALTER TABLE VENDAS ADD CONSTRAINT VENDAS_CONSUMO FOREIGN KEY VENDAS_CONSUMO (CONSUMO_ID_CONSUMO)
    REFERENCES CONSUMO (ID_CONSUMO);

-- Reference: VENDAS_EMPRESAS (table: VENDAS)
ALTER TABLE VENDAS ADD CONSTRAINT VENDAS_EMPRESAS FOREIGN KEY VENDAS_EMPRESAS (EMPRESAS_CNPJ)
    REFERENCES EMPRESAS (CNPJ);

-- Reference: VENDAS_USUARIOS (table: VENDAS)
ALTER TABLE VENDAS ADD CONSTRAINT VENDAS_USUARIOS FOREIGN KEY VENDAS_USUARIOS (USUARIOS_ID_USUARIO)
    REFERENCES USUARIOS (ID_USUARIO);

-- End of file.

