-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-03-28 22:24:46.48

-- tables
-- Table: CIDADES
CREATE TABLE CIDADES (
    CID_ID_CIDADE int NOT NULL,
    CID_DES_CIDADE varchar(30) NOT NULL,
    CID_DES_SIGLA_ESTADO varchar(2) NOT NULL,
    CID_DES_REGIAO_IBGE varchar(12) NOT NULL,
    CONSTRAINT CIDADES_pk PRIMARY KEY (CID_ID_CIDADE)
);

-- Table: CNAE
CREATE TABLE CNAE (
    CNA_ID_CNAE int NOT NULL,
    CNA_COD_CNAE int NOT NULL,
    CNA_DES_CNAE varchar(100) NOT NULL,
    CONSTRAINT CNAE_pk PRIMARY KEY (CNA_ID_CNAE)
);

-- Table: CONSUMO
CREATE TABLE CONSUMO (
    CON_MES_REFERENCIA timestamp NOT NULL,
    CON_QTD_CONSUMO int NULL,
    EMPRESAS_EMP_NUM_CNPJ int NOT NULL
);

-- Table: EMPRESAS
CREATE TABLE EMPRESAS (
    EMP_NUM_CNPJ int NOT NULL,
    EMP_ORIGEM int NOT NULL,
    CIDADES_CID_ID_CIDADE int NOT NULL,
    CNAE_CNA_ID_CNAE int NOT NULL,
    CONSTRAINT EMPRESAS_pk PRIMARY KEY (EMP_NUM_CNPJ)
);

-- foreign keys
-- Reference: CONSUMO_EMPRESAS (table: CONSUMO)
ALTER TABLE CONSUMO ADD CONSTRAINT CONSUMO_EMPRESAS FOREIGN KEY CONSUMO_EMPRESAS (EMPRESAS_EMP_NUM_CNPJ)
    REFERENCES EMPRESAS (EMP_NUM_CNPJ);

-- Reference: EMPRESAS_CIDADES (table: EMPRESAS)
ALTER TABLE EMPRESAS ADD CONSTRAINT EMPRESAS_CIDADES FOREIGN KEY EMPRESAS_CIDADES (CIDADES_CID_ID_CIDADE)
    REFERENCES CIDADES (CID_ID_CIDADE);

-- Reference: EMPRESAS_CNAE (table: EMPRESAS)
ALTER TABLE EMPRESAS ADD CONSTRAINT EMPRESAS_CNAE FOREIGN KEY EMPRESAS_CNAE (CNAE_CNA_ID_CNAE)
    REFERENCES CNAE (CNA_ID_CNAE);

-- End of file.

