-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-05-25 00:51:07.271

-- tables
-- Table: CARTEIRA
CREATE TABLE CARTEIRA (
    ID_CARTEIRA bigint NOT NULL,
    USUARIOS_ID_USUARIO bigint NOT NULL,
    CONSTRAINT CARTEIRA_pk PRIMARY KEY (ID_CARTEIRA)
);

-- Table: CIDADE
CREATE TABLE CIDADE (
    ID_CIDADE bigint NOT NULL,
    DES_CIDADE varchar(100) NOT NULL,
    DES_SIGLA_ESTADO char(2) NOT NULL,
    DES_REGIAO_IBGE varchar(20) NOT NULL,
    CONSTRAINT CIDADE_pk PRIMARY KEY (ID_CIDADE)
);

-- Table: CNAE
CREATE TABLE CNAE (
    ID_CNAE bigint NOT NULL,
    COD_CNAE varchar(50) NOT NULL,
    DES_CNAE varchar(200) NOT NULL,
    UNIQUE INDEX CNAE_ak_1 (COD_CNAE),
    CONSTRAINT CNAE_pk PRIMARY KEY (ID_CNAE)
);

-- Table: CONSUMO
CREATE TABLE CONSUMO (
    ID_CONSUMO bigint NOT NULL,
    CIDADE_ID_CIDADE bigint NOT NULL,
    CNAE_ID_CNAE bigint NOT NULL,
    QTD_CONSUMO int NOT NULL,
    MES_REFERENCIA timestamp NOT NULL,
    EMPRESA_ID_EMPRESA bigint NOT NULL,
    USUARIOS_ID_USUARIO bigint NOT NULL,
    CONSTRAINT CONSUMO_pk PRIMARY KEY (ID_CONSUMO)
);

-- Table: EMPRESA
CREATE TABLE EMPRESA (
    ID_EMPRESA bigint NOT NULL,
    CNPJ varchar(20) NOT NULL,
    ORIGEM varchar(20) NOT NULL,
    UNIQUE INDEX EMPRESA_ak_1 (CNPJ),
    CONSTRAINT EMPRESA_pk PRIMARY KEY (ID_EMPRESA)
);

-- Table: USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO bigint NOT NULL,
    NOME varchar(255) NOT NULL,
    EMAIL varchar(255) NOT NULL,
    SENHA varchar(255) NOT NULL,
    NIVEL varchar(40) NOT NULL,
    TIPO varchar(30) NOT NULL,
    FLAG_CARTEIRA bool NOT NULL,
    UNIQUE INDEX USUARIOS_ak_1 (EMAIL),
    CONSTRAINT USUARIOS_pk PRIMARY KEY (ID_USUARIO)
);

-- foreign keys
-- Reference: CARTEIRA_USUARIOS (table: CARTEIRA)
ALTER TABLE CARTEIRA ADD CONSTRAINT CARTEIRA_USUARIOS FOREIGN KEY CARTEIRA_USUARIOS (USUARIOS_ID_USUARIO)
    REFERENCES USUARIOS (ID_USUARIO);

-- Reference: CONSUMO_CIDADE (table: CONSUMO)
ALTER TABLE CONSUMO ADD CONSTRAINT CONSUMO_CIDADE FOREIGN KEY CONSUMO_CIDADE (CIDADE_ID_CIDADE)
    REFERENCES CIDADE (ID_CIDADE);

-- Reference: CONSUMO_CNAE (table: CONSUMO)
ALTER TABLE CONSUMO ADD CONSTRAINT CONSUMO_CNAE FOREIGN KEY CONSUMO_CNAE (CNAE_ID_CNAE)
    REFERENCES CNAE (ID_CNAE);

-- Reference: CONSUMO_EMPRESA (table: CONSUMO)
ALTER TABLE CONSUMO ADD CONSTRAINT CONSUMO_EMPRESA FOREIGN KEY CONSUMO_EMPRESA (EMPRESA_ID_EMPRESA)
    REFERENCES EMPRESA (ID_EMPRESA);

-- Reference: CONSUMO_USUARIOS (table: CONSUMO)
ALTER TABLE CONSUMO ADD CONSTRAINT CONSUMO_USUARIOS FOREIGN KEY CONSUMO_USUARIOS (USUARIOS_ID_USUARIO)
    REFERENCES USUARIOS (ID_USUARIO);

-- End of file.

